INSERT INTO USER (VC_NAME, VC_EMAIL, VC_PASSWORD, NU_STATUS, DT_REGISTER) 
VALUES('ADOLFO DARIO CCANTO LLACTAHUAMAN', 'adolmit@gmail.com', '$2a$10$VWJi7UHjUr6KhZcldu0yS.MjIfXWepBq17Im2lNPAaVFeyz0UcJF6', 1, '2018-04-03');
INSERT INTO USER (VC_NAME, VC_EMAIL, VC_PASSWORD, NU_STATUS, DT_REGISTER) 
VALUES('CAST GROUP', 'administrador.ferias@castgroup.com.br', '$2a$10$Vq8NWxcarKr8TrfLBi4gKupMQE6lddD2jdjylhLB1Cg6kK.B9RMD.', 1, '2018-03-08');


INSERT INTO EQUIPE(VC_NAME, NU_STATUS, DT_REGISTER) VALUES('EQUIPE FRONTEND', 1, '2017-01-08');
INSERT INTO EQUIPE(VC_NAME, NU_STATUS, DT_REGISTER) VALUES('EQUIPE BACKEND', 1, '2017-01-08');
INSERT INTO EQUIPE(VC_NAME, NU_STATUS, DT_REGISTER) VALUES('EQUIPE BANCO DE DATOS', 1, '2017-01-08');

INSERT INTO FUNCIONARIO(NU_ID_EQUIPE, VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(1,'CARLOS ROJAS', '1996-06-20','2017-07-01','/images/foto/crojas.png', 1, '2017-07-01');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(1,'CESAR POLANCO', '1990-04-10','2018-06-06','/images/foto/cpolanco.png', 1, '2018-06-01');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(1,'JHONATAN VENANCIO', '1985-05-11','2019-05-06','/images/foto/jvenancio.png', 1, '2019-05-01');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(2,'WILLIAM LUQUE', '1984-06-22','2017-07-01','/images/foto/wluque.png', 1, '2017-07-01');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(2,'MILAGROS MANRIQUE', '1998-11-16','2018-04-03','/images/foto/mmanrique.png', 1, '2018-04-01');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(3,'JULIO LOPEZ', '1997-08-13','2016-11-12','/images/foto/jlopez.png', 1, '2016-11-11');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(3,'CARLA YUPANQUI', '1992-03-02','2018-08-01','/images/foto/cyupanqui.png', 1, '2017-08-01');
INSERT INTO FUNCIONARIO(NU_ID_EQUIPE,VC_NAME, DT_NASCIMIENTO, DT_CONTRATO, VC_URL_FOTO, NU_STATUS, DT_REGISTER) 
VALUES(3,'MIRIAM CARBAJAL', '1988-12-03','2018-08-01','/images/foto/mcarbajal.png', 1, '2017-08-01');

INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(1, 'RUA CELESTE','1011','PERTO DO MERCADO', 'SAN LUIS', 'RECIFE', 'PERNAMBUCO', 1, '2017-07-01');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(2, 'RUA AZUL','0310','PERTO DO BANCO ITAU', 'SAO JOAO', 'RECIFE', 'PERNAMBUCO', 1, '2018-06-01');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(3, 'RUA VERDE','0421','PERTO DO METRO', 'SAN CARLOS', 'RECIFE', 'PERNAMBUCO', 1, '2019-05-01');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(4, 'RUA BRANCA','6022','PERTO DO DROGARIA', 'SAN MARCOS', 'RECIFE', 'PERNAMBUCO', 1, '2017-07-01');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(5, 'RUA GRIS','5050','PERTO DO MERCADO', 'SAN JOSE', 'RECIFE', 'PERNAMBUCO', 1, '2018-04-01');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(6, 'RUA AMARILLO','6050','PERTO DO ESCOLA', 'SANTA MARIA', 'RECIFE', 'PERNAMBUCO', 1, '2016-11-11');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(7, 'RUA SALINAS','3350','PERTO DO RIO', 'SANTA MARTA', 'RECIFE', 'PERNAMBUCO', 1, '2017-08-01');
INSERT INTO ADDRESS(NU_ID_FUNCIONARIO, VC_RUA, VC_NUMERO, VC_COMPLEMENTO, VC_BAIRRO, VC_CIDADE, VC_ESTADO, NU_STATUS, DT_REGISTER) 
VALUES(8, 'RUA CANELA','8304','PERTO DO UNIVERSIDADE', 'SAN MATEO', 'RECIFE', 'PERNAMBUCO', 1, '2017-08-01');








